export const COMMON_ICON = {
  SearchIcon: 'search-icon',
  ShopIcon: 'shop-icon',
  ShoppingCartIcon: 'shopping-cart-icon',
  EmailIcon: 'email-icon',
  FacebookIcon: 'facebook-icon',
  PhoneIcon: 'phone-icon',
  PlusIcon: 'plus-icon',
  HeartIcon: 'heart-icon',
  AccountIcon: 'account-icon',
  StarIcon: 'star-icon',
  MinusIcon: 'minus-icon',
  ChefHatIcon: 'chef-hat-icon',
  DeliveryIcon: 'delivery-icon',
  MailIcon: 'mail-icon',
  CallIcon: 'call-icon',
  MapIcon: 'map-icon',
  SunIcon: 'sun-icon',
  EyeIcon: 'eye-icon',
  EyeSlashIcon: 'eye-slash-icon',
}
