export const COMMON_COLOR = {
  ORANGE: 'bg-red-300',
  HOVER_ORANGE: 'hover:bg-red-600',
  TEXT_WHITE: 'text-white',
  TEXT_GRAY_STRONG: 'text-gray-900',
  TEXT_GRAY_BRIGHT: 'text-gray-700',
}

export const COLOR_BUTTON = {
  ADD_PRODUCT: COMMON_COLOR.ORANGE,
  HOVER_ADD_PRODUCT: COMMON_COLOR.HOVER_ORANGE,
}

export const COLOR_CARD = {
  TEXT_PRODUCT: COMMON_COLOR.TEXT_GRAY_BRIGHT,
  TEXT_PRICE: COMMON_COLOR.TEXT_GRAY_STRONG,
}